version: 2

models:
  - name: stg_sales__customers
    description: "This model contains information about customers"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer"
        tests:
            - unique
            - not_null
  - name: stg_sales__order
    description: "This model contains information about orders placed by users, including the status of each order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: order_status
        description: "The current status of the order."
        tests:
          - accepted_values:
              name: accepted_values_order_status
              values: [1,2,3,4]
      - name: staff_id
        description: "Foreign key linking the order to the staff who placed it."
        tests:
          - relationships:
              name: staff_id_id_foreign_key_in_stg_sales__order
              to: ref('stg_sales__staffs')
              field: staff_id
      - name : store_id 
        description: "Foreign key linking the order to the store"
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_sales__order
              to: ref('stg_sales__stores')
              field: store_id

  - name: stg_sales__order_item
    description: "This model contains information about each item included in an order, including its price, quantity, and shipping cost."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_id_foreign_key_in_stg_sales__order_item
              to: ref('stg_sales__order')
              field: order_id
      - name: total_order_item_amount
        description: "The total amount for this order item, calculated as (price * quantity) + shipping_cost."

  - name: stg_sales__staffs
    description: "This model contains information about staffs"
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff."
        tests:
            - unique
            - not_null
  - name: stg_sales__stores
    description: "This model contains details for stores"
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each stores."
        tests:
            - unique
            - not_null